const CONSTANT_TYPES = {
    FETCH_COUNTRIES_START: 'FETCH_COUNTRIES_START',
    FETCH_COUNTRIES_SUCCESS: 'FETCH_COUNTRIES_SUCCESS',
    FETCH_COUNTRIES_FAILURE: 'FETCH_COUNTRIES_FAILURE',
    SET_COUNTRY_SELECTED: 'SET_COUNTRY_SELECTED',
    FETCH_ALL_START: 'FETCH_ALL_START',
    FETCH_ALL_SUCCESS: 'FETCH_ALL_SUCCESS',
    FETCH_ALL_FAILURE: 'FETCH_ALL_FAILURE'
}

export default CONSTANT_TYPES;